---
CSR1:
  username: "avi"
  password: "cisco"
  # platform: "ios"
  hostname: "10.0.0.41"
  auth_strict_key: false
  # groups:
  #   # - cisco_group
  #   - europe

CSR2:
  username: "avi"
  password: "cisco"
  # platform: "ios"
  hostname: "10.0.0.42"
  auth_strict_key: false
  # groups:
  #   # - cisco_group
  #   - usa
